src/color-alias.json

fix: correct naming of neutral-background-color-default

---

src/color-alias.json

Fixes typo introduced in #23 that was breaking the build in CSS.
We should have tests for this.

fix: correct typo that was breaking the build

---

src/component-layout.json

radio-button-selection-indicator was missing
DNA-1156

fix: radio-button-selection-indicator was missing

---

yarn.lock

The style-dictionary-sets parser for drover was setting color tokens to wireframe.  This updates the dependency to pick up that patch (2.0.1).
I didn't open an issue
I like fixing things

fix: drover parser setting colors to wireframe

---

package.json
tasks/diffOutput.sh

Adds a tool that will diff either `variables.json` or `drover.json` against the last package published.  Hacky a bit because it relies on the `unpkg` CDN, not fiddling about with git tags etc.  But it works.

chore: added a thing to diff last release dist with local

---

src/component-layout.json

The nested `sets` block was missing for a few Radio Button tokens
https://jira.corp.adobe.com/browse/CSS-229
Bug
Rebuilt CSS, problem gone
Before
After
- Bug fix (non-breaking change which fixes an issue)

fix: unbreak nested sets (CSS-229)

---

src/component-layout.json

from Cable Hicks:
> `tooltip-width` and `tooltip-height` should be `tooltip-tip-width` and `tooltip-tip-height` according to the specs.
The token `tooltip-maximum-width` does not have a name update change.

fix: switch tooltip-width and height to tooltip-tip-width

---

.npmignore

Had some trouble with the automated release from https://github.com/adobe/spectrum-tokens/pull/82. This pr should fix it.

Trigger release

---

package.json
tasks/deprecateExpress.js
tasks/lib/augmentExpressTokens.js
test/__snapshots__/deprecateExpress.test.js.snap
test/deprecateExpress.test.js

Added a task that augments all the express tokens with deprecation metadata:
```json
{
"deprecated": true,
"deprecated_comment":
"Express will merge with Spectrum with the release of Spectrum 2.",
}
```
Express and Spectrum sets will converge in Spectrum 2 with the exception of a couple of alias tokens that we will provide as CSS custom property overrides rather than storing them in the token system.
I added some tests to verify it is only adding data on the express tokens.

chore: add deprecateExpress task

---

src/layout-component.json

This length value for token `combo-box-visual-to-field-button-quiet` is currently `0`, instead of `0px`, which throws off some CSS calc() results, making them invalid (or requires multiplying this token by 1px).
This fix makes this value consistent with the rest of the token values in the repo, which all specify 0 length values as `0px`. The only other `0` within tokens is for an opacity (which is okay).
I am currently working on the core token migration for the Combobox component in spectrum-css, which is using this token. It currently required multiplying it by 1px in the calc as a workaround. Adding or subtracting `0` instead of `0px` in a CSS calc() [is invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#notes) and gives unexpected results. This change would allow removal …

fix: add 'px' to zero length value in combobox token

---

.github/workflows/release.yml
src/layout-component.json
src/layout.json

New Picker specific token:
* `picker-end-edge-to-disclosure-icon-quiet`
New layout tokens:
* `field-top-to-disclosure-icon-75`
* `field-top-to-disclosure-icon-100`
* `field-top-to-disclosure-icon-200`
* `field-top-to-disclosure-icon-300`
* `field-end-edge-to-disclosure-icon-75`
* `field-end-edge-to-disclosure-icon-100`
* `field-end-edge-to-disclosure-icon-200`
* `field-end-edge-to-disclosure-icon-300`
[DNA-1273](https://jira.corp.adobe.com/browse/DNA-1273)
Frank has identified an area that needed some adjustments – the spacing around the disclosure icon inside the Picker. The summary is that the field-end-edge-to-disclosure-icon-size token can't be applied to the `edge` spacing in the quiet Picker like the non-quiet version. So instead, we'll define the top/bottom differently than the …

Added picker and field tokens

---

.changeset/rotten-oranges-mate.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

*Tokens added (2):*
- `floating-action-button-drop-shadow-y`
- `floating-action-button-shadow-color`
[DNA-1283](https://jira.corp.adobe.com/browse/DNA-1283)
Adding a couple tokens to floating action button that should have been included earlier.

Added new floating action button tokens, closes DNA-1283

---

.changeset/tricky-bears-grow.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Removed express specific token data for color handle and color loupe.
*Tokens values updated (7):*
- `color-handle-drop-shadow-blur`
- `color-handle-drop-shadow-x`
- `color-handle-drop-shadow-y`
- `color-handle-outer-border-opacity`
- `color-handle-outer-border-width`
- `color-handle-size`
- `color-handle-size-key-focus`
*Newly deprecated tokens (1):*
- `color-handle-drop-shadow-color`
[DNA-1279](https://jira.corp.adobe.com/browse/DNA-1279)
Adobe Express does not need a separate design for Color loupe and Color handle components. They will be using the Spectrum component instead.

Update color loupe and color handle

---

.changeset/odd-planets-sell.md
packages/tokens/src/layout-component.json

These tokens updated were missed in https://github.com/adobe/spectrum-tokens/commit/853d8c36569f800284d6c9f7ce7a49ec6dc2eb99 and so they didn't get released with [@adobe/spectrum-tokens@12.6.0](https://github.com/adobe/spectrum-tokens/releases/tag/%40adobe%2Fspectrum-tokens%4012.6.0)
[DNA-1279](https://jira.corp.adobe.com/browse/DNA-1279)
:art:  Design changes:
Express will be using Spectrum Color loupe - no specific differences between the two themes for this component anymore.
Token value change
*Token values updated (4):*
- `color-loupe-bottom-to-color-handle` (removed express specific token data)
- `color-loupe-height` (removed express specific token data)
- `color-loupe-inner-border-width` (removed express specific token data)
- `color-loupe-width` (removed express specific token …

Removed express specific token data for color handle

---

.changeset/tough-waves-drive.md
packages/tokens/src/color-component.json

[DNA-1279](https://jira.corp.adobe.com/browse/DNA-1279)
Adobe Express does not need a separate design for Color loupe and Color handle components. They will be using the Spectrum component instead.

Updated color-handle remove express specific value

---

.changeset/lazy-pans-give.md
.github/workflows/deploy-visualizer.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

The `component` name field had some typos in the coach mark component; this pr fixes them.
The tokens with updated `component` metadata (all set to "coach-mark"):
* `coach-mark-minimum-width`
* `coach-mark-edge-to-content`
* `coach-mark-pagination-text-to-bottom-edge`
* `coach-mark-width`
* `coach-mark-media-minimum-height`
* `coach-mark-media-height`
* `coach-mark-title-size`
* `coach-mark-body-size`
* `coach-mark-pagination-body-size`

fix(tokens): typo for coachmark in component field

---

.changeset/proud-pants-burn.md
packages/tokens/src/layout-component.json

Fixed typo with `picker-end-edge-to-disclosure-icon-quiet` by adding a new token and deprecating `picker-end-edge-to-disclousure-icon-quiet`.
_Token added (1):_
* `picker-end-edge-to-disclosure-icon-quiet`
_Newly deprecated token (1):_
* `picker-end-edge-to-disclousure-icon-quiet`
@karstens pointed out the spelling error.

Fix token typo

---

package.json
packages/tokens/tasks/buildManifest.js
pnpm-lock.yaml

Building the manifest file would create a file missing the trailing blank space, which must be run through prettier to be fixed. I fixed the `buildManifest` task to run the file contents through prettier before writing the file.

Fixed manifest task

---

.changeset/sharp-actors-serve.md
packages/tokens/package.json
pnpm-lock.yaml

This migrates the graphql and other devDeps from the tokens package into a devDependency so that these do not get installed for downstream users.
resolves #151

fix: move dependencies to devDeps in tokens package

---

.changeset/strong-tables-cheer.md
packages/tokens/src/layout-component.json

Renamed `meter-default-width` to `meter-width`
[DNA-1297](https://jira.corp.adobe.com/browse/DNA-1297)
> We try to avoid "default" in the name (unless it's the state) because it's a word that implies that it's relative to something else that may not be named, which could get confusing. So meter-width I think for the name, and then just add a note in the specs.

Renamed meter-default-width to meter-width

---

.changeset/olive-feet-fetch.md
packages/tokens/src/color-aliases.json
packages/tokens/src/color-component.json

Added `wireframe` values to 2 color tokens.
_Tokens update (2):_
- `opacity-checkerboard-square-dark`
- `overlay-opacity`
Running some tests, I found 2 color tokens were missing `wireframe` values in the sets.

Missing `wireframe` values

---

.changeset/warm-experts-beg.md
packages/tokens/src/color-palette.json

transparent-white-900 & transparent-black-900 values where rgb() but have alphas set; should be rgba().
Data consistency.

fix: rgb used instead of rgba for a couple tokens

---

.changeset/neat-weeks-turn.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/src/layout.json
pnpm-lock.yaml

Adjusted navigational indicator spacing tokens to accommodate larger indicator icon sizes.
_Token values updated (4):_
- `navigational-indicator-top-to-back-icon-small`: `desktop` `7px` -> `6px` and `mobile` `9px` -> `7px`
- `navigational-indicator-top-to-back-icon-medium`: `desktop` `11px` -> `9px` and `mobile` `13px` -> `12px`
- `navigational-indicator-top-to-back-icon-large`: `desktop` `14px` -> `12px` and `mobile` `17px` -> `16px`
- `navigational-indicator-top-to-back-icon-extra-large`: `desktop` `17px` -> `15px` and `mobile` `22px` -> `19px`
[DNA-1324](https://jira.corp.adobe.com/projects/DNA/issues/DNA-1324?filter=allopenissues)
Updated size for the Arrow UI icon used in submenus (previously, it was too small and looked imbalanced relative to everything else)

Navigation indicator spacing tweaks

---

.changeset/heavy-brooms-teach.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/src/typography.json
pnpm-lock.yaml

cjk-letter-spacing & detail-letter-spacing should have the same type schema, this aligns them both to "dimension"
Token type consistency.

fix: aligns letter-spacing token schemas to "dimension" for consistency

---

.changeset/tame-bobcats-beg.md
packages/tokens/src/color-aliases.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7146431716
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/17

feat: updates from spectrum-tokens-studio-data

---

.changeset/eight-months-cheer.md
packages/tokens/schemas/token-types/color-set.json
packages/tokens/src/icons.json
packages/tokens/src/semantic-color-palette.json
pnpm-lock.yaml

Newly defined S2 Icon colors by the Icons team were incorporated into our system. This includes updates to existing colors and new color additions. More details on icon colors can be found [in this document](https://paper.dropbox.com/doc/S2-Icon-colors-May-update--CPQCbAN3uvmfSCYV5UekAgYkAg-BqbGyRAAL87Ehoqm9WrCB) and [this Figma file](https://www.figma.com/design/KRqwJWgLuW4R7HwFUzKWiB/S2-Icon-color?node-id=0%3A1&t=jRZwm9gOH4dyLwL7-1).
Icons team defined new S2 color tokens needed for their iconography assets.

S2 Icon color updates

---

.changeset/clean-snails-cheer.md
packages/tokens/schemas/token-types/color-set.json
packages/tokens/schemas/token-types/scale-set.json
packages/tokens/src/color-aliases.json
packages/tokens/src/color-component.json
packages/tokens/src/color-palette.json
packages/tokens/src/icons.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/semantic-color-palette.json
packages/tokens/src/typography.json
packages/tokens/tasks/addIds.js
pnpm-lock.yaml

Added UUIDs to the base of tokens with `sets` properties.
@shirlsli requested the UUIDs to make it easier to make comparisons for the updated Token Diff tool. This will be particularly helpful in the cases where a token is converted from a set to a single value or when a token is renamed.
I updated the token schema for the sets tokens so an error is thrown when a UUID is not included.
- [ x I have added tests to cover my changes.

Added UUIDs to set tokens

---

tools/diff-generator/src/index.js
tools/diff-generator/src/lib/deprecated-token-detection.js
tools/diff-generator/src/lib/renamed-token-detection.js
tools/diff-generator/test/addedToken.test.js
tools/diff-generator/test/deletedToken.test.js
tools/diff-generator/test/deprecatedToken.test.js
tools/diff-generator/test/renamedToken.test.js
tools/diff-generator/test/test-schemas/added-deprecated-token.json
tools/diff-generator/test/test-schemas/deprecated-token.json
tools/diff-generator/test/test-schemas/several-deprecated-tokens.json
tools/diff-generator/test/test-schemas/several-renamed-deprecated-tokens.json
tools/diff-generator/test/updatedToken.test.js

Created a function to detect newly deprecated tokens with some basic tests to check functionality on mock schema.
Currently, there isn't an ability to see what tokens have been marked deprecated in the diff generator.
- Basic test with one token checking if the diff generator detects that it's been changed to deprecated
- Test with one new deprecated token and one former token marked to deprecated
- Test with same tokens and properties (two are deprecated, two aren't) but renamed to check if the diff generator knows that they aren't newly deprecated; they're old tokens whose names have been changed
- Test with more than one new deprecated token

Created function to detect newly deprecated tokens with some basic tests

---

.changeset/flat-parrots-cry.md
packages/tokens/src/layout-component.json
packages/tokens/src/semantic-color-palette.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9652026396
Contains changes from the following prs:
* [S2 Color - Deprecation of negative-subdued-background tokens](https://github.com/adobe/spectrum-tokens-studio-data/pull/138)
* [Updated contextual help tokens for S2](https://github.com/adobe/spectrum-tokens-studio-data/pull/137)

Updated contextual help tokens for S2

---

.changeset/wet-apricots-tickle.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10089563243
Tokens Studio Data PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/150
Updated S2 swatch tokens and added swatch-group tokens in S2 Color and S2 Non-color data sets, respectively. 
**_Color_**
- swatch-border-color
- swatch-group-border-color
**_Non-color_**
- swatch-border-opacity
- swatch-disabled-icon-border-opacity
- swatch-group-spacious-spacing
- swatch-group-border-opacity
Swatch and swatch group components are being formalized as Spectrum 2 components. These tokens define the design data needed for implementation. Changes include updated corner rounding, colors and spacing for spacious density.

Updated S2 Swatch and introduced S2 Swatch-group tokens

---

.changeset/curly-pants-enjoy.md
packages/tokens/src/color-aliases.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10096356349
https://github.com/adobe/spectrum-tokens-studio-data/pull/152
Added dragged drop shadow tokens that point to new 300 global drop shadow tokens
This update includes x, y, and blur values as well as new color tokens and variables
This also fixes the token type of the non-color drop-shadow sizing tokens
These are new foundational drop shadow tokens that represent a higher elevation when items are dragged. The more prominent shadow also brings more visual focus to the dragged item. They will be used in the standard panel "dragged" state, as well as in future component updates, to be determined.

Added dragged drop shadow tokens

---

.changeset/wicked-rings-knock.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10291410913
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/153
- Updated avatar size tokens, including all sizes from `75` to `700`
- Added new avatar size tokens, from `800` to `1500`
- Added new avatar border thickness and color tokens
- Added avatar group size tokens, from `50` to `500`
- Added avatar group spacing tokens, from `50` to `500`
- Avatar: added new sizes and updated existing sizes to better match other components and work across a variety of use cases.
- ⚠️ Important note: Accepting updates from this release will update the avatar sizes. The largest change in size is 8px. In some cases, you may want to relink to a new size. View the migration guide below to …

Updated avatar and avatar group tokens

---

.changeset/metal-colts-scream.md
packages/tokens/src/layout-component.json
packages/tokens/src/typography.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10292339876
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/162
- Updated tokens:
- code-cjk-strong-font-weight
- code-cjk-strong-emphasized-font-weight
- Added new tokens:
- code-cjk-size-xl
- code-cjk-size-l
- code-cjk-size-m
- code-cjk-size-s
- code-cjk-size-xs
- Reordered existing `code-size-*` tokens to go from XL to XS
These code token updates include some fixes to CJK font-weights to match the Latin font-weights when possible. We added CJK size tokens for consistency with other typography style tokens. Note that the new CJK size tokens currently point to the default code font-size tokens since Source Code Pro handles Latin and CJK sizing comparably.

Updated code tokens for S2

---

packages/tokens/src/color-aliases.json

`overlay-opacity` is marked as deprecated and seems to be a mistake.

Undeprecate overlay-opacity

---

.changeset/brave-dragons-sparkle.md
packages/tokens/src/layout-component.json
packages/tokens/src/typography.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10686025072
Design Motivation
The S1 type token changes fix some minor issues with CJK font-sizing, font-weight, and removes the added letter-spacing (since we got feedback this was unnecessary and both latin and CJK characters look too spaced out with the current letter-spacing applied)

S1 typography update for CJK improvements

---

packages/tokens/src/color-component.json

`standard-panel-gripper-color-drag` was mistakenly declared as a color-set token with identical values for the `light` and `dark` values.
`standard-panel-gripper-color-drag` was mistakenly set as a color-set token with identical values for the `light` and `dark` sets. The problem doesn't currently exist in the [adobe/spectrum-tokens-studio-data](https://github.com/adobe/spectrum-tokens-studio-data) repo.

Fix duplicate set values

---

.changeset/eleven-cougars-guess.md
package.json
pnpm-lock.yaml
tools/diff-generator/src/lib/cli.js
tools/diff-generator/test/cli.test.js
tools/diff-generator/test/fileImport.test.js

Previously, the tests used whatever `pnpm tdiff` would use, including the globally installed package.

Use local package instead of installed package

---

.changeset/forty-moons-train.md
tools/diff-generator/package.json
tools/diff-generator/src/lib/cli.js
tools/diff-generator/test/cli.test.js
tools/diff-generator/update-version.js

It's tricky to read in the package json file version number for the cli to return for `tdiff --version`. I added a prepare script to the package json that will find and replace the hardcoded version number in the `src/lib/cli.js` file.
Locally only. We won't be able to know if it's working for sure without publishing the package.

Added `prepare` script to update cli hardcoded version number

---

tools/diff-generator/src/lib/renamed-token-detection.js

diff-generator incorrectly identifies token renames due to an invalid uuid comparison. Both objects being compared should be first checked for valid uuids before comparing the uuids otherwise there can be a false positive when neither object has a uuid.
https://jira.corp.adobe.com/browse/DNA-1376
v48 to v49 cli comparison

fix: diff-gen - incorrect identification of renamed tokens

---

tools/diff-generator/src/lib/updated-token-detection.js

diff-generator explicitly looks for token values of type 'string', but we introduced support for type 'number'. This checks the additional value type so the reporting of the value change is consistent with strings.
https://jira.corp.adobe.com/browse/DNA-1376
v48 to v49 cli comparison

fix: diff-gen - supports token values that are numeric

---

.changeset/fresh-cameras-learn.md
tools/diff-generator/src/lib/cli.js

diff-generator muddles the deprecated token reporting as it doesn't handle undefined deprecated comments.
https://jira.corp.adobe.com/browse/DNA-1377
v48 to v49 cli comparison

fix: diff-gen - fixes deprecation messages when missing deprecation comment

---

tools/diff-generator/src/lib/deprecated-token-detection.js
tools/diff-generator/test/addedToken.test.js
tools/diff-generator/test/test-schemas/added-set-tokens-out-of-order.json

Changes to token deprecation were not being detected when the deprecation was being done in sets, rather than at the root. Also true for un-deprecating tokens.
https://jira.corp.adobe.com/browse/DNA-1379
v47 to v48 cli comparison

fix: diff-gen - deprecation in sets not being detected

---

.changeset/three-buttons-hunt.md
packages/tokens/src/layout-component.json

Change takeover dialog dimensions to use percentages which were previously converted to ems by mistake.
**Updated Tokens (2):**
- `takeover-dialog-height`: `1.00em` -> `1.00%`
- `takeover-dialog-width`: `1.00em` -> `1.00%`

fix takeover dialog dimensions types

---

.changeset/fair-bats-travel.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11615565038
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/209

S2 tree view tokens

---

.changeset/cool-eyes-nail.md
docs/site/public/schemas/token-types/gradient-stop.json
docs/site/public/schemas/token-types/text-align.json
docs/site/public/schemas/token-types/token.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/12398787947

S2 Action Bar and Checkbox values

---

.changeset/s2-tokens-viewer-improvements.md
docs/s2-tokens-viewer/index.html
docs/s2-tokens-viewer/package.json
docs/s2-tokens-viewer/packages/tokens/src/color-aliases.json
docs/s2-tokens-viewer/packages/tokens/src/color-component.json
docs/s2-tokens-viewer/packages/tokens/src/color-palette.json
docs/s2-tokens-viewer/packages/tokens/src/icons.json
docs/s2-tokens-viewer/packages/tokens/src/layout-component.json
docs/s2-tokens-viewer/packages/tokens/src/layout.json
docs/s2-tokens-viewer/packages/tokens/src/semantic-color-palette.json
docs/s2-tokens-viewer/packages/tokens/src/typography.json
pnpm-lock.yaml

- Add workspace dependency on `@adobe/spectrum-tokens` package
- Add prepare script to automatically copy token files locally
- Update file paths to use relative paths instead of absolute paths
- Make viewer fully self-contained with local token files
The S2 Tokens Viewer was pointing to the folder structure of the monorepo instead of using the correct package directory and copying them to a local directory.

Fix s2 tokens viewer

---

.changeset/rare-zebras-confess.md
docs/s2-tokens-viewer/tokens/package.json
docs/site/package.json
packages/component-schemas/package.json
packages/tokens/package.json
pnpm-lock.yaml
tools/diff-generator/package.json
tools/token-csv-generator/package.json
tools/token-manifest-builder/package.json
tools/transform-tokens-json/package.json

When attempting to upgrade the version of the token diff utility, we received the following warning:
```
file:///Users/cassondrar/Projects/spectrum-css/node_modules/@adobe/token-diff-generator/src/lib/file-import.js:15
import { glob } from "glob";
^^^^
SyntaxError: Named export 'glob' not found. The requested module 'glob' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'glob';
const { glob } = pkg;
at ModuleJob._instantiate (node:internal/modules/esm/module_job:175:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:258:5)
at async ModuleLoader.import (node:internal/modules/esm/loader:540:24)
at async asyncRunEntryPointWithESMLoader …
```

fix(deps): missing glob dependency

---

.github/workflows/release.yml

This PR fixes a shell parsing error in the release GitHub Action workflow that was causing the "Commit updated release timeline data" step to fail.
Fixes the GitHub Action error seen in recent releases where the commit step failed with exit code 1.
The release workflow was failing on the final step due to a multi-line commit message with embedded newlines causing shell parsing issues. This prevented the release timeline data from being properly committed back to the repository.
- Reviewed shell script syntax and git commit message formatting
- Verified the fix follows git best practices for commit titles and bodies
- Checked that conditional logic handles edge cases properly
N/A - GitHub Action workflow fix
On branch fix/release-workflow-commit-message
nothing to commit, working tree …

fix(ci): resolve release timeline commit message shell parsing error

---

.changeset/24aeff17e430.md
packages/tokens/src/color-component.json
tools/component-diff-generator/src/cli.js
tools/diff-generator/src/lib/cli.js
tools/token-changeset-generator/src/cli.js

**Source PR**: [#283 SDS-15337: Standard panel gripper color update](https://github.com/adobe/spectrum-tokens-studio-data/pull/283)
**Automated sync via**: [GitHub Actions Run](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/17330507087)
---
Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/17330507087

SDS-15337: Standard panel gripper color update
