tokens/color-alias.json
tokens/color-semantic.json
tokens/color.json
tokens/component-layout.json

This adds the current state of beta colors (3/16/22)

feat: adding colors

---

tokens/color-alias.json
tokens/color-semantic.json
tokens/color.json
tokens/component-layout.json
tokens/layout.json

This flattens the data structure to make dots unnecessary in references

feat: flatten structures so dots go away

---

package.json

Add build to release workflow

---

tokens/color.json

it is black, but should be white. It's a black and white issue.

fix: white is should be rgb(255, 255, 255)

---

package.json
yarn.lock

We were having issues with multiple layers of references.
A simplified example of the use case can be seen in the [tests on the style-dictionary-sets project](https://github.com/GarthDB/style-dictionary-sets/blob/main/tests/fixtures/multi-depth.json).

Fix nested refs issue

---

tokens/color.json

Adding the 'wireframe' color theme
DNA-1143
I add the wireframe data or I get the hose
By looking at it and going 'yep'
The screenshots are not at all appropriate

feat: adds wireframe as a color theme

---

tokens/color.json

Updating most of the gray colors for mostly dark and darkest to get WCAG 2.1 right.
DNA-1147 is the epic that covers this
WCAG 2.1 is important and we hold ourselves to a very high bar.
LOLOLOLOLOLOL ... I checked with Nate
nope
- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.

fix: update gray values for WCAG 2.1 goodness

---

tokens/layout.json

Moving CJK to front of token name
DNA-1125 and DNA-1126
- [x ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.

feat: rename CJK line height tokens

---

tokens/color-alias.json
tokens/color-semantic.json

Add neutral background colors

---

config.js
package.json
tokens/color-alias.json
yarn.lock

Use latest formatter to fix token name collision

---

tokens/color-alias.json

feat: adding accent and negative background color

---

tokens/color-semantic.json

No, really.  Just adding positive semantic colors.
DNA-1151
We are positive we need positive color semantics

feat: adds positive color semantic for DNA-1151

---

README.md

Temporary better language for the readme.

fix: update readme to call out beta

---

README.md

This updates the readme on main to call out the beta

fix: update readme to call out beta FOR MAIN

---

src/color-alias.json

Adds informative background color aliases
DNA-1152

feat: adds informative background aliases

---

src/component-layout.json
src/layout.json

Fixes #25
Incorrect object structure.
Locally tested with `spectrum-tokens-css`
Before:
```
{
value: '8px',
filePath: 'node_modules/@adobe/spectrum-tokens/src/layout.json',
isSource: true,
original: { value: '8px' },
name: 'spectrum-corner-radius-200-sets-spectrum-desktop',
attributes: { sets: [ 'spectrum' ] },
path: [ 'corner-radius-200', 'sets', 'spectrum', 'desktop' ]
}
```
After:
```
{
value: '8px',
filePath: 'node_modules/@adobe/spectrum-tokens/src/layout.json',
isSource: true,
original: { value: '8px' },
name: 'spectrum-corner-radius-200-sets-spectrum-sets-desktop',
attributes: { sets: [ 'spectrum', 'desktop' ] },
path: [ 'corner-radius-200', 'sets', 'spectrum', 'sets', 'desktop' ]
}
```

fix: correct nested sets, they were missing another sets object

---

src/component-layout.json

Adds tooltip max width tokens
DNA-1148

feat: tooltip max width

---

src/color-alias.json

adding positive background color aliases
DNA-1149

feat: adds postive background colors

---

src/component-layout.json

adds toast tokens for DNA-1153 (branch name and commit message are wrong)
DNA-1153

feat: adds toast tokens for DNA-1153

---

src/component-layout.json

removes component-minimum-width

feat: removes component-minimum-width

---

src/component-layout.json

adding action bar tokens
DNA-1161

feat: adding action bar tokens

---

src/color-alias.json

Added tokens for these 3 backgrounds:
* `background-base-color`
* `background-layer-1-color`
* `background-layer-2-color`

feat: adding tokens for 3 backgrounds

---

src/component-layout.json

Added express values to the following tokens:
| Name                              | Value                                                                                                                              |
|-----------------------------------|------------------------------------------------------------------------------------------------------------------------------------|
| switch-control-width-small        | 23 px (Spectrum / desktop)<br>32 px (Spectrum / mobile)<br>25 px (Spectrum Express / desktop)<br>32 px (Spectrum Express / mobile) |
| switch-control-width-medium       | 26 px (Spectrum / desktop)<br>36 px (Spectrum / mobile)<br>28 px (Spectrum Express / desktop)<br>36 px (Spectrum Express / mobile) |
| switch-control-width-large        | 29 px (Spectrum / …

Add Express sizes to Swatch tokens

---

.gitignore
src/component-layout.json

Adds progress bar, inline-alert, and fixes a bug
DNA-1164, DNA-1165

feat: adds progress bar and in-line alert

---

src/component-layout.json

adds missing express data for radio tokens
DNA-1166

feat: adds missing express data for radio tokens

---

src/component-layout.json

fixes a bug with radio values
I didn't create an issue :)

fix: set for radio value was broken

---

package.json
yarn.lock

Update style-dictionary-sets dependency

---

package.json
yarn.lock

This will fix what Drover requested for a format update (remove `drover` from the base of the output structure).

Update latest style-dictionary-sets

---

yarn.lock

fix: upgrade sets to get fix for drover parser

---

src/component-layout.json

adds values for popover and tag

feat: add popover and tag tokens

---

src/component-layout.json

updating the help text icon spacing values
DNA-1171

fix: update help text icon spacing

---

src/component-layout.json

Added `swatch`
|Token Name|Value|
|:----|:----|
|swatch-size-extra-small|16 px (desktop)<br />20 px (mobile)|
|swatch-size-small|24 px (desktop)<br />30 px (mobile)|
|swatch-size-medium|32 px (desktop)<br />40 px (mobile)|
|swatch-size-large|40 px (desktop)<br />50 px (mobile)|
|swatch-rectangle-width-multiplier|2|
|swatch-slash-thickness-extra-small|2 px|
|swatch-slash-thickness-small|3 px|
|swatch-slash-thickness-medium|4 px|
|swatch-slash-thickness-large|5 px|

Add Swatch Tokens

---

src/color-alias.json

Added
```json
"overlay-color": {
"ref": "{black}",
"value": "rgb(0, 0, 0)"
},
"overlay-opacity": {
"sets": {
"light": {
"value": "0.4"
},
"dark": {
"value": "0.5"
},
"darkest": {
"value": "0.6"
}
}
},
```

feat: added overlay-color and overlay-opacity values

---

src/color-alias.json

Adds drop shadow color for wireframe
DNA-1198

feat: drop shadow color for wireframe

---

.releaserc

Fixing semantic release config and forcing release.

Fixing release config

---

tasks/diff.js

Before the diff would just list all tokens that have been potentially changed:
example:
```
*Tokens possibly renamed (2):*
- `focus-indicator-gap`
- `focus-indicator-thickness`
```
Now it lists all the possible new name options (tokens that have different names, but the same values):
```
*Tokens possibly renamed (2):*
- Old name: `focus-indicator-gap`, new name options:
- `focus-indicator-thickness-2`
- `focus-indicator-gap-2`
- Old name: `focus-indicator-thickness`, new name options:
- `focus-indicator-thickness-2`
- `focus-indicator-gap-2`
```
If there's only one new token that has a matching value:
```
*Tokens possibly renamed (1):*
- `focus-indicator-gap` -> `focus-indicator-gap-2`
```

Added some formatting to the potential renames console

---

src/component-layout.json

This adds alert dialog tokens; closes DNA-1223
DNA-1223
I want to get a free t-shirt

feat: adds alert dialog tokens; closes DNA-1223

---

src/color-alias.json

fixing bugs in notice and visual color data
DNA-1222

fix: orange bugs in notice and visual color

---

src/component-layout.json

adds thumbnail tokens
DNA-1221

feat: adds thumbnail tokens (DNA-1221)

---

src/color-alias.json
src/layout.json

add border-400 and opacity-disabled
DNA-1221

feat: add border-400 and opacity-disabled

---

src/component-layout.json

Renames meter-thickness-medium to meter-thickness large
DNA-1224

feat: rename meter-thickness-medium; closes DNA-1224

---

src/typography.json

Some typography tokens used `spectrum for express` instead of `express`.

Typo in typography.json

---

src/color-component.json
src/layout-component.json
src/typography.json

Added `component` data to token src. Output is not impacted.

refactor: added component structure to component tokens

---

src/color-component.json
src/layout-component.json

Adding color control tokens, plus navigational thingy
DNA-1234, DNA-1235, DNA-1236, DNA-1238

New color control tokens

---

src/layout-component.json

Missing units on `toast-maximum-width`

Missing units on `toast-maximum-width`

---

src/color-aliases.json
src/color-component.json
src/layout-component.json
src/layout.json
src/typography.json

* added neutral-background-color-selected tokens
* added missing color-slider color tokens:
* `color-slider-border-color`
* `color-slider-border-opacity`
* fixed typo in token name:
* renamed `color-wheel-area-margin` to `color-wheel-color-area-margin`
* reorganized tokens to align with Excel document better for easier comparisons
* [DNA-1233](https://jira.corp.adobe.com/browse/DNA-1233)
* [DNA-1238](https://jira.corp.adobe.com/browse/DNA-1238)
* [DNA-1235](https://jira.corp.adobe.com/browse/DNA-1235)

Fixes and formatting

---

src/layout.json

Added `field-width` token.
- [DNA-1239](https://jira.corp.adobe.com/browse/DNA-1239)

Added field-width token

---

src/layout-component.json
src/layout.json

Added search field and illustrated message tokens
- [DNA-1247](https://jira.corp.adobe.com/browse/DNA-1247) New search field token
- [DNA-1248](https://jira.corp.adobe.com/browse/DNA-1248) New illustrated message tokens

Search field and illustrated message tokens

---

manifest.json
package.json
tasks/buildManifest.js
yarn.lock

I added a `manifest.json` file that contains a list of the json files in the `src` directory. I also included a build script to build updates to the file easily.
The token visualizer tool needs a list of the json files to import from the package.

Added manifest.json and a script to generate it

---

.lintstagedrc.json
src/color-component.json
src/layout-component.json
src/typography.json

Added new component tokens:
* New alert dialog tokens ([DNA-1255](https://jira.corp.adobe.com/browse/DNA-1255))
* New and modified Color wheel tokens ([DNA-1256](https://jira.corp.adobe.com/browse/DNA-1256))
* New detail typography tokens: text transform ([DNA-1257](https://jira.corp.adobe.com/browse/DNA-1257))
* New Drop zone tokens ([DNA-1258](https://jira.corp.adobe.com/browse/DNA-1258))
Fixed missing set tokens in color loupe

New Tokens: Alert Dialog, Dropzone, Colorwheel

---

src/color-component.json
src/layout-component.json
src/layout.json
test/deprecateExpress.test.js
test/drover.test.js

New tokens:
* color handle, [DNA-1261](https://jira.corp.adobe.com/browse/DNA-1261)
* accordion, [DNA-1269](https://jira.corp.adobe.com/browse/DNA-1269)
* coach mark, [DNA-1271](https://jira.corp.adobe.com/browse/DNA-1271)
* menu item, [DNA-1260](https://jira.corp.adobe.com/browse/DNA-1260)
* picker-width [DNA-1268](https://jira.corp.adobe.com/browse/DNA-1268)
Updated token:
* updated color-slider-minimum-length, [DNA-1238](https://jira.corp.adobe.com/browse/DNA-1238)

Add color handle, accordion, coach mark, menu item tokens

---

.lintstagedrc.json
src/layout-component.json
tasks/diff.js

Tokens were mistakenly named in the excel file; this pr fixes it but adds aliases for the old names with deprecation metadata until the next major release.
https://jira.corp.adobe.com/browse/DNA-1278

Token Typo

---

.changeset/forty-pots-joke.md
.github/workflows/ci.yml
packages/tokens/package.json
packages/tokens/src/layout-component.json

Adds new "tray-top-to-content-area" token
* Closes [DNA-1276](https://jira.corp.adobe.com/projects/DNA/issues/DNA-1276)

Added tray token

---

.github/workflows/release.yml

ci: fix workflow error

---

.changeset/cool-rats-hang.md
packages/tokens/package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

New Side navigation (component) tokens:
* `side-navigation-width`
* `side-navigation-minimum-width`
* `side-navigation-maximum-width`
* `side-navigation-second-level-edge-to-text`
* `side-navigation-third-level-edge-to-text`
* `side-navigation-with-icon-second-level-edge-to-text`
* `side-navigation-with-icon-third-level-edge-to-text`
* `side-navigation-item-to-item`
* `side-navigation-item-to-header`
[DNA-1277](https://jira.corp.adobe.com/browse/DNA-1277)
:art:  Design changes:
Navigation item background tokens use a solid color
Navigation item background (selected) use a solid color

Sidenav Tokens

---

.changeset/curvy-ravens-tell.md
packages/tokens/src/layout-component.json

*Tokens added (4):*
- `slider-control-to-field-label-extra-large`
- `slider-control-to-field-label-large`
- `slider-control-to-field-label-medium`
- `slider-control-to-field-label-small`
[DNA-1284](https://jira.corp.adobe.com/browse/DNA-1284)
:color-palette: Design updates:
Updated the slider control height to be following component-height-## instead (this was already the case in our previous token system) in order to maintain the click area of the track. No visual changes.

Update Slider Tokens

---

.changeset/cool-apes-invent.md
package.json
packages/tokens/src/color-component.json
pnpm-lock.yaml

fixed token name typo
- [DNA-1289](https://jira.corp.adobe.com/browse/DNA-1289)
🎨 from Design:
"I made a mistake in the name for Floating Action Button token for drop shadow, I've updated the spreadsheet so it now reads "floating-action-button-drop-shadow-color" previously the word "drop" was missing. All other instances should be good. "

Update to Floating Action Button shadow token

---

.changeset/hip-insects-enjoy.md
packages/tokens/src/color-aliases.json
packages/tokens/src/layout-component.json

Added tokens for tabs
<details><summary>*Tokens added (51):*</summary>
- `accent-content-color-selected`
- `neutral-subdued-content-color-selected`
- `tab-item-bottom-to-text-compact-extra-large`
- `tab-item-bottom-to-text-compact-large`
- `tab-item-bottom-to-text-compact-medium`
- `tab-item-bottom-to-text-compact-small`
- `tab-item-bottom-to-text-extra-large`
- `tab-item-bottom-to-text-large`
- `tab-item-bottom-to-text-medium`
- `tab-item-bottom-to-text-small`
- `tab-item-compact-height-extra-large`
- `tab-item-compact-height-large`
- `tab-item-compact-height-medium`
- `tab-item-compact-height-small`
- `tab-item-focus-indicator-gap-extra-large`
- `tab-item-focus-indicator-gap-large`
- `tab-item-focus-indicator-gap-medium`
- `tab-item-focus-indicator-gap-small`
- …

Tab tokens

---

.changeset/stale-eagles-mix.md
packages/tokens/src/color-aliases.json
packages/tokens/src/layout-component.json

Previously published tab tokens were missing uuids
<details><summary><h3>Tokens updated (51):</h3></summary>
- `accent-content-color-selected`
- `neutral-subdued-content-color-selected`
- `tab-item-bottom-to-text-compact-extra-large`
- `tab-item-bottom-to-text-compact-large`
- `tab-item-bottom-to-text-compact-medium`
- `tab-item-bottom-to-text-compact-small`
- `tab-item-bottom-to-text-extra-large`
- `tab-item-bottom-to-text-large`
- `tab-item-bottom-to-text-medium`
- `tab-item-bottom-to-text-small`
- `tab-item-compact-height-extra-large`
- `tab-item-compact-height-large`
- `tab-item-compact-height-medium`
- `tab-item-compact-height-small`
- `tab-item-focus-indicator-gap-extra-large`
- `tab-item-focus-indicator-gap-large`
- `tab-item-focus-indicator-gap-medium`
- …

fix(tokens): added uuids to tab tokens

---

packages/tokens/test/checkId.test.js

Just a simple test based on Cable's work to add UUIDs to each token value; it checks if an ID is present and unique.
I accidentally published a release with some tokens missing IDs.
Locally.

Added a test to check UUIDs of tokens

---

.changeset/nine-cycles-battle.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Table tokens added
<details><summary><strong>Tokens added (88):</strong></summary>
- `table-border-divider-width`
- `table-checkbox-to-text`
- `table-column-header-row-bottom-to-text-extra-large`
- `table-column-header-row-bottom-to-text-large`
- `table-column-header-row-bottom-to-text-medium`
- `table-column-header-row-bottom-to-text-small`
- `table-column-header-row-top-to-text-extra-large`
- `table-column-header-row-top-to-text-large`
- `table-column-header-row-top-to-text-medium`
- `table-column-header-row-top-to-text-small`
- `table-edge-to-content`
- `table-header-row-checkbox-to-top-extra-large`
- `table-header-row-checkbox-to-top-large`
- `table-header-row-checkbox-to-top-medium`
- `table-header-row-checkbox-to-top-small`
- `table-row-bottom-to-text-extra-large-compact`
- …

feat(tokens): added table tokens, closes DNA-1274

---

.moon/tasks.yml

Just some clean-up of moon config.

chore: update moon, remove scaffold tasks

---

.changeset/swift-gifts-dress.md
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Graduating the pre-release snapshot release of the in-field button.
_Tokens added (19):_
- `in-field-button-edge-to-disclosure-icon-stacked-extra-large`
- `in-field-button-edge-to-disclosure-icon-stacked-large`
- `in-field-button-edge-to-disclosure-icon-stacked-medium`
- `in-field-button-edge-to-disclosure-icon-stacked-small`
- `in-field-button-edge-to-fill`
- `in-field-button-fill-stacked-inner-border-rounding`
- `in-field-button-inner-edge-to-disclosure-icon-stacked-extra-large`
- `in-field-button-inner-edge-to-disclosure-icon-stacked-large`
- `in-field-button-inner-edge-to-disclosure-icon-stacked-medium`
- `in-field-button-inner-edge-to-disclosure-icon-stacked-small`
- `in-field-button-outer-edge-to-disclosure-icon-stacked-extra-large`
- …

In field button

---

docs/site/lib/components.js
docs/site/package.json
docs/visualizer/package.json
package.json
packages/tokens/CHANGELOG.md
packages/tokens/manifest.json
packages/tokens/package.json
packages/tokens/tasks/addIds.js
packages/tokens/tasks/buildManifest.js
packages/tokens/tasks/deprecateExpress.js
packages/tokens/test/checkId.test.js
packages/tokens/test/schemaValidator.test.js
pnpm-lock.yaml
tools/token-manifest-builder/src/index.js

Update all dependencies

---

.changeset/tiny-balloons-study.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Add new menu-item token for section dividers.
_Tokens added (1):_
- `menu-item-section-divider-height`
[DNA-1296](https://jira.corp.adobe.com/browse/DNA-1296)

New menu-item token for section dividers

---

.changeset/dull-buckets-run.md
packages/tokens/src/layout-component.json

_Tokens added (6):_
- `coach-mark-maximum-width`
- `coach-mark-media-height`
- `coach-mark-width`
_Token values updated (1):_
- `coach-mark-minimum-width`: `mobile` from `208px` to `216px`
- `coach-mark-title-size`: added `desktop` value
- `coach-mark-body-size`: added `desktop` value
- `coach-mark-pagination-body-size`: added `desktop` value
[DNA-1311](https://jira.corp.adobe.com/browse/DNA-1311)
There were a few missing tokens from the excel spreadsheet as well as some updates, want to make sure they're captured here.

Updated coach-mark tokens

---

.changeset/curly-numbers-serve.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/src/icons.json
pnpm-lock.yaml

Initial icon tokens added.
Token Diff
*Tokens added (6):*
- `icon-color-blue-primary-default`
- `icon-color-green-primary-default`
- `icon-color-inverse`
- `icon-color-primary-default`
- `icon-color-red-primary-default`
- `icon-color-yellow-primary-default`
* [DNA-1317](https://jira.corp.adobe.com/browse/DNA-1317) Update icon tokens
To prepare icon tokens for variables, we need to update SVG-native tokens:
Updated token values that will be imported for Token Studio:
`icon-color-yellow-primary-default`
Updated token values that won't be needed in Token Studio but have value updates:
`icon-color-yellow-primary-hover`
`icon-color-yellow-primary-down`

Icon Tokens

---

.changeset/pretty-beds-march.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/manifest.json
packages/tokens/moon.yml
packages/tokens/tasks/addIds.js
packages/tokens/test/checkManifest.test.js
pnpm-lock.yaml

Updated `manifest.json` file to include `src/icons.json` and updated tests and tasks to make sure it isn't overlooked in the future.

Fix manifest file

---

package.json
packages/tokens/tasks/diff.js
pnpm-lock.yaml

A minor update to the diff task that accepts a tag or specific version for the npm package to compare against.
For example:
```sh
moon run tokens:generateDiffResult -- beta
```
When that is run, the task will pull the latest release to the `beta` tag to use as a comparison base.

Update diff report generator task to accept tag argument

---

package.json
packages/tokens/tasks/diff.js
pnpm-lock.yaml

A minor update to the diff task that accepts a tag or specific version for the npm package to compare against.
For example:
```sh
moon run tokens:generateDiffResult -- beta
```
When that is run, the task will pull the latest release to the `beta` tag to use as a comparison base.

Update diff report generator task to accept tag argument (beta)

---

.changeset/strong-hornets-shake.md
packages/tokens/src/icons.json
packages/tokens/src/layout.json

Added UI icon sizes
_Tokens added (46):_
- `arrow-icon-size-100`
- `arrow-icon-size-200`
- `arrow-icon-size-300`
- `arrow-icon-size-400`
- `arrow-icon-size-500`
- `arrow-icon-size-600`
- `arrow-icon-size-75`
- `asterisk-icon-size-100`
- `asterisk-icon-size-200`
- `asterisk-icon-size-300`
- `asterisk-icon-size-75`
- `checkmark-icon-size-100`
- `checkmark-icon-size-200`
- `checkmark-icon-size-300`
- `checkmark-icon-size-400`
- `checkmark-icon-size-50`
- `checkmark-icon-size-500`
- `checkmark-icon-size-600`
- `checkmark-icon-size-75`
- `chevron-icon-size-100`
- `chevron-icon-size-200`
- `chevron-icon-size-300`
- `chevron-icon-size-400`
- `chevron-icon-size-50`
- `chevron-icon-size-500`
- `chevron-icon-size-600`
- `chevron-icon-size-75`
- `corner-triangle-icon-size-100`
- …

UI icon sizes

---

.changeset/neat-pets-rhyme.md
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Modified and new Side nav tokens
*Tokens added (1):*
- `side-navigation-header-to-item`
*Token values updated (1):*
- `side-navigation-item-to-header`
* [DNA-1295](https://jira.corp.adobe.com/browse/DNA-1295)
Category headings changed to Adobe Clean 12 Medium @ `gray-600`, to differentiate them from multi-level, top navigation items.

Modified and new Side nav tokens

---

.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Moved `color-loupe-drop-shadow-y` and `color-loupe-drop-shadow-blur` from `src/color-component.json` to `src/layout-component.json` because they are dimensions and not colors.
This doesn't impact the output in `dist` since the file name isn't taken into consideration, but it does help to have the `src` directory organized.

Moved color loupe tokens

---

.changeset/lemon-lizards-walk.md
.github/workflows/deploy-docs.yml
.moon/toolchain.yml
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Fixing a bug; `contextual-help-body-size` is referencing heading instead of body typography tokens.
[DNA-1326](https://jira.corp.adobe.com/browse/DNA-1326)
Most likely a typo

contextual-help-body-size typo

---

docs/visualizer/package.json
pnpm-lock.yaml

Updated deps used in the token visualizer.

Update visualizer deps

---

.changeset/short-bees-smile.md
packages/tokens/schemas/token-types/font-size.json
packages/tokens/schemas/token-types/scale-set.json
packages/tokens/src/typography.json

Added font-size token schema
Tokens with update $schema (15):
- font-size-50
- font-size-75
- font-size-100
- font-size-200
- font-size-300
- font-size-400
- font-size-500
- font-size-600
- font-size-700
- font-size-800
- font-size-900
- font-size-1000
- font-size-1100
- font-size-1200
- font-size-1300
Brings the schema closer to Tokens Studio typing.

feat(tokens): added font-size token $schema

---

.changeset/empty-steaks-dress.md
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7479630402
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/29

feat: updates from spectrum-tokens-studio-data

---

docs/visualizer/README.md

Updates to the token visualizer README.md file to match the public repo information.
#242

Update visualizer README.md, closes #242

---

.changeset/beige-hats-taste.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.husky/commit-msg
.moon/toolchain.yml
package.json
packages/tokens/schemas/token-types/system-set.json
packages/tokens/src/icons.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
pnpm-lock.yaml

Consolidates token sets that do not differ in value.

feat: remove duplicate token set definitions (S1)

---

.changeset/smooth-turtles-retire.md
package.json
packages/tokens/package.json
packages/tokens/src/color-aliases.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
pnpm-lock.yaml

Consolidates token sets that do not differ in value.

feat: remove duplicate token set definitions (S2)

---

.changeset/real-seals-camp.md
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8176535245
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/67

S2 Alert banner and search field token updates

---

.changeset/angry-zoos-applaud.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8190615517
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/68

Updating, adding, and deprecating tokens for text field and text area

---

.changeset/twelve-impalas-compare.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8190626341
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/69

S2 toast and color area non-color token updates

---

.github/workflows/ci.yml
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
package.json

Small changes to the GitHub workflows
Fix warnings in GitHub Actions for using an older Node version and deprecated workflow.
CI config change only.

Updating GitHub workflows

---

packages/tokens/package.json

Adding config to let the npm package publish with a generated provenance statement.
Details on [NPM](https://docs.npmjs.com/generating-provenance-statements) documentation
from the [NPM docs](https://docs.npmjs.com/generating-provenance-statements):
> You can generate provenance statements for the packages you publish. This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.

Adding NPM Provenance to publishing process

---

.changeset/sour-rabbits-own.md
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8270300396
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/72

Adding Title typography tokens

---

.changeset/silly-radios-float.md
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8288839817
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/75

S2 Opacity checkerboard non-color token updates

---

.changeset/good-baboons-doubt.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
package.json
packages/tokens/src/color-aliases.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8381634875
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/78

S2 Title Color

---

.changeset/chatty-turtles-sell.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8526512565
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/85

S2 Tag and Picker token updates

---

.changeset/sour-wasps-sparkle.md
package.json
packages/tokens/src/color-aliases.json
packages/tokens/src/layout.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8530002974
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/84

Updated and added S2 drop shadow tokens

---

.changeset/five-steaks-argue.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8557580341
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/89

S2 Combo box, In-field button and In-field progress circle updates

---

.changeset/lazy-bears-remember.md
packages/tokens/index.js
packages/tokens/package.json
packages/tokens/src/layout-component.json
packages/tokens/test/checkUniqueTokenNames.js
pnpm-lock.yaml

I added tests to check for duplicate token names across all of the files combined. I also fixed the problem of duplicate tokens in `layout-component.json`
It turns out that when you parse JSON with duplicate tokens, it just replaces the first instance of the name with the last instance it reads, so it never failed with duplicate names previously.

Removed duplicate tokens

---

.moon/toolchain.yml
docs/site/moon.yml
docs/site/package.json
docs/visualizer/moon.yml
docs/visualizer/package.json
package.json
packages/tokens/index.js
packages/tokens/moon.yml
packages/tokens/package.json
packages/tokens/test/checkId.test.js
packages/tokens/test/checkManifest.test.js
packages/tokens/test/checkUniqueTokenNames.js
packages/tokens/test/componentSchemaValidator.test.js
packages/tokens/test/deprecateExpress.test.js
packages/tokens/test/drover.test.js
packages/tokens/test/schemaValidator.test.js
packages/tokens/test/schemaValidators/alias.test.js
packages/tokens/test/tokenSchemaValidator.test.js
pnpm-lock.yaml

Many of these changes have been done in `beta` as that's where we're working the most, but I wanted to bring these changes into the `main` branch as well.
Tested locally

Update tests and dependencies in main

---

.changeset/config.json
.github/workflows/ci.yml
.github/workflows/deploy-docs.yml
.github/workflows/release.yml
.moon/toolchain.yml
.moon/workspace.yml
docs/site/moon.yml
moon.yml
package.json
packages/tokens/package.json
packages/tokens/tasks/diff.js
pnpm-lock.yaml
test/validateWorkflows.js

- Updated a couple more dependencies
- Added validation tests for GitHub workflow actions
Locally

chore: updated deps, added tests, updated changeset changelog

---

.changeset/fluffy-bees-play.md
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8727811438
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/100

Updated values for component pill edge to visual only tokens

---

packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8728148450
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/104

Updated status light tokens

---

packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8728154764
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/105

Updated desktop and mobile values for alert-banner-top-to-workflow-icon

---

packages/tokens/src/color-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8899957574
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/125

S2 Popover border token - color only, re-do

---

.changeset/silver-pianos-share.md
.moon/toolchain.yml
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8915120902
Token Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/124

Updated illustrated message and drop zone tokens

---

.changeset/yellow-chefs-rhyme.md
.moon/toolchain.yml
package.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
pnpm-lock.yaml

Adding S2 corner rounding to the S2 foundations
This change adds a set of corner rounding tokens to the Spectrum design system. These changes are documented on the S2 [website](https://s2.spectrum.corp.adobe.com/page/object-styles/#overview).

Snapshot s2 foundations corner radius

---

.github/workflows/release-snapshot.yml

minor testing for automated snapshot release.

Testing automated snapshot release

---

pnpm-lock.yaml
tools/diff-generator/moon.yml
tools/diff-generator/src/index.js
tools/diff-generator/test/addedNewToken.test.js
tools/diff-generator/test/renameChecker.test.js
tools/diff-generator/test/test-schemas/added-renamed-tokens.json
tools/diff-generator/test/test-schemas/entire-schema-renamed.json
tools/diff-generator/test/test-schemas/new-token.json
tools/diff-generator/test/test-schemas/several-added-tokens.json

Created a function to detect new tokens and moved the code for looping through the schema to a helper function. This is because I want to reduce the repetitiveness of my code. 
This change is needed to detect new tokens based on UUID instead of the token name. Moving the schema traversal code to a helper function seemed like best practice since it is needed in multiple functions with very little difference in syntax (only difference are the conditions which is solved via passing in a function).
Currently, this feature has not been tested. My next task is to write the tests.

Created detect new tokens function and moved looping through schema into helper function

---

.changeset/twelve-kangaroos-rescue.md
.moon/toolchain.yml
docs/site/public/schemas/token-types/color-set.json
package.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9457236619
Updated tokens according to updated token spec for Spectrum 2, including new and deprecated tokens
https://github.com/adobe/spectrum-tokens-studio-data/pull/136

Updated breadcrumbs tokens for S2

---

packages/component-schemas/index.js
packages/component-schemas/test/index.test.js

fix: schema path checks

---

.changeset/neat-sloths-bake.md
packages/tokens/src/color-aliases.json
packages/tokens/src/icons.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9701106553

S2 foundations: icon sizing and spacing

---

.changeset/strong-trains-crash.md
package.json
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9666207255
Contains changes from this pr https://github.com/adobe/spectrum-tokens-studio-data/pull/143

Add coach indicator tokens

---

.changeset/khaki-teachers-do.md
packages/tokens/src/color-aliases.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9859612401
Tokens studio data pr:
* https://github.com/adobe/spectrum-tokens-studio-data/pull/147
* https://github.com/adobe/spectrum-tokens-studio-data/pull/146

Updated S2 Accordion and Meter tokens

---

docs/visualizer/package.json
pnpm-lock.yaml

This should fix the broken visualizer

Updating dependencies for the token visualizer

---

.changeset/sixty-poems-tap.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10088819340
* https://github.com/adobe/spectrum-tokens-studio-data/pull/144 : Updated thumbnail size tokens and added new tokens
* https://github.com/adobe/spectrum-tokens-studio-data/pull/149 : Updated S2 Action bar tokens

S2 Updated thumbnail size tokens and updated action bar tokens

---

.changeset/hungry-hornets-hang.md
tools/diff-generator/package.json

The package was published with the incorrect author data, this pr fixes the issue.

Added missing author data to @adobe/token-diff-generator

---

.changeset/strange-panthers-watch.md
packages/tokens/schemas/token-types/color-set.json
packages/tokens/src/color-aliases.json
packages/tokens/src/color-palette.json
packages/tokens/src/semantic-color-palette.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10623083328
https://github.com/adobe/spectrum-tokens-studio-data/pull/189

Colors update for S2-foundations

---

packages/tokens/schemas/token-types/text-align.json

New token schema type for text alignment.
We have new tokens coming in from tokens studio with a similar type.

Add text-align token schema

---

packages/tokens/schemas/token-types/text-align.json

This is the same as #411, but for the beta/s2 branch
#411 
We have new tokens coming in from tokens studio with a similar type.

Add text align token schema (s2/beta)

---

.husky/commit-msg
.husky/pre-commit
.moon/toolchain.yml
package.json
packages/tokens/index.js
packages/tokens/package.json
packages/tokens/src/color-component.json
packages/tokens/src/icons.json
packages/tokens/test/checkComponentProps.js
packages/tokens/test/checkSetsUnique.js
pnpm-lock.yaml

Tokens in the icon file did not always have the

Missing component data in Icon

---

.changeset/tender-monkeys-flash.md
packages/tokens/schemas/token-types/gradient-stop.json
packages/tokens/src/color-aliases.json
packages/tokens/src/color-component.json
packages/tokens/src/color-palette.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/semantic-color-palette.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10511818984
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/161
Updated tokens for the S2 Table component in S2 layout.component set.
table-column-header-row-top-to-text-medium
table-row-top-to-text-medium-regular
table-row-bottom-to-text-medium-regular
table-row-top-to-text-medium-spacious
table-header-row-checkbox-to-top-medium
table-row-checkbox-to-top-medium-compact
table-row-checkbox-to-top-medium-regular
table-row-checkbox-to-top-medium-spacious
Added new token to the S2 layout set:
side-focus-indicator
Tokens changes are reflected in both desktop and mobile sets.
Table component is being formalized as a Spectrum 2 component. These updated tokens define the design data …

Updated S2 Table tokens

---

.changeset/proud-oranges-think.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/typography.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11170922445
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/199

S2 typography, heading

---

docs/visualizer/public/json/typography.json
packages/tokens/schemas/token-types/multiplier.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/typography.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11183800625

S2 typography, detail

---

docs/visualizer/public/json/typography.json
packages/tokens/schemas/token-types/multiplier.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/typography.json

Reverts adobe/spectrum-tokens#420

Revert "S2 typography, detail"

---

.husky/commit-msg
.husky/pre-commit
docs/site/package.json
docs/site/public/schemas/token-types/color-set.json
docs/site/public/schemas/token-types/gradient-stop.json
docs/site/public/schemas/token-types/multiplier.json
docs/site/public/schemas/token-types/scale-set.json
docs/site/public/schemas/token-types/text-align.json
docs/site/public/schemas/token-types/token.json
docs/visualizer/package.json
package.json
packages/tokens/package.json
packages/tokens/schemas/token-types/color-set.json
packages/tokens/schemas/token-types/gradient-stop.json
packages/tokens/schemas/token-types/scale-set.json
packages/tokens/schemas/token-types/token.json
packages/tokens/src/layout-component.json
packages/tokens/src/typography.json
pnpm-lock.yaml
tools/diff-generator/package.json

Updating all the package dependencies, and the JSON schema from the `beta` branch (s2).
Repo maintenance.

Update deps and token schema

---

.changeset/dirty-terms-shop.md
.husky/commit-msg
.husky/pre-commit
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11445137825
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/207

Cleaning up corner radius to match s2-foundations proposal

---

tools/diff-generator/src/lib/formatterCLI.js
tools/diff-generator/src/lib/formatterMarkdown.js

chore: code cleanup

---

packages/tokens/src/color-palette.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11961994350
https://github.com/adobe/spectrum-tokens-studio-data/pull/165

S2 Foundations non-gray-800 colors update

---

.changeset/fifty-knives-glow.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/12402907836

S2 Color Wheel Tokens

---

.changeset/purple-llamas-stare.md
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/12418896743
Spectrum Tokens Studio Data PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/216

Added component-size-maximum-perspective-down token

---

.changeset/spicy-days-fetch.md
packages/tokens/src/color-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/13209671468
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/220

SDS-14254 Popover - border color update

---

.changeset/lucky-files-fail.md
packages/tokens/src/color-palette.json
pnpm-lock.yaml

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/13268540294
Spectrum Tokens Studio Data PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/219

SDS-14641 Static gradient colors

---

.changeset/beige-hounds-invent.md
packages/tokens/src/color-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/13318158639
Spectrum Tokens Studio Data PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/222

SDS-14325 Action bar - border color update

---

docs/site/public/diff.html

docs: added diff.html

---

.changeset/little-eyes-grow.md
packages/tokens/src/color-component.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/13950513243
Tokens Studio PRs:
* https://github.com/adobe/spectrum-tokens-studio-data/pull/228
* https://github.com/adobe/spectrum-tokens-studio-data/pull/227

S2 Card Tokens

---

.changeset/curly-zebras-shake.md
packages/tokens/schemas/token-types/color-set.json
packages/tokens/src/color-aliases.json
packages/tokens/src/color-component.json
packages/tokens/src/color-palette.json
packages/tokens/src/icons.json
packages/tokens/src/semantic-color-palette.json
packages/tokens/test/checkSetsUnique.js

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/14252944673
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/225

SDS-14676 Tokens: Add Wireframe theme

---

.changeset/clever-chicken-show.md
.moon/toolchain.yml
package.json
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/15077831295
Tokens Studio PRs:
- https://github.com/adobe/spectrum-tokens-studio-data/pull/253
- https://github.com/adobe/spectrum-tokens-studio-data/pull/248

Tag field and missing icon tokens

---

.github/workflows/release-snapshot.yml

This github workflow lived in the s2 foundations branch and is super helpful for making snapshot releases from a branch.
This PR just brings it into main.

Update snapshot release workflow

---

.changeset/strong-brooms-change.md
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/15220883113
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/257

Accordion update

---

.changeset/eager-breads-cover.md
packages/component-schemas/schemas/components/select-box.json
packages/component-schemas/schemas/components/text-area.json

Additional changes that should have been included in https://github.com/adobe/spectrum-tokens/pull/520

Updating component options for s2, batch1

---

.changeset/every-meals-eat.md
packages/tokens/schemas/token-types/token.json
packages/tokens/schemas/token-types/typography.json
packages/tokens/src/layout-component.json
packages/tokens/src/layout.json
packages/tokens/src/typography.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/16152319266
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/254

Composite Typography tokens

---

.changeset/wet-cherries-flash.md
packages/tokens/src/layout-component.json

Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/16178030866
Tokens Studio PR: https://github.com/adobe/spectrum-tokens-studio-data/pull/266

Fixed accordion token values due to changelog error

---

.github/workflows/token-diff-pr-comment.yml

Fixed token diff pr comment workflow

Fixed token diff pr comment workflow

---

.github/workflows/publish-optimized-diff.yml
tools/optimized-diff/package.json

First publish of optimized diff package

---

.changeset/drop-shadow-and-color-s2-changes.md
docs/s2-tokens-viewer/tokens/color-aliases.json
docs/s2-tokens-viewer/tokens/color-palette.json
docs/s2-tokens-viewer/tokens/layout.json
docs/s2-tokens-viewer/tokens/package.json
packages/tokens/schemas/token-types/drop-shadow.json
packages/tokens/schemas/token-types/token.json
packages/tokens/src/color-aliases.json
packages/tokens/src/color-palette.json
packages/tokens/src/layout.json

**Source PR**: [#286 feat: updates from spectrum-tokens sync](https://github.com/adobe/spectrum-tokens-studio-data/pull/286)
**Automated sync via**: [GitHub Actions Run](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/17274624553)
---
Created by Action: https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/17274624553

Drop Shadow and Color s2 changes

---

.changeset/1756508200-spectrum-design-data-mcp-docs.md
tools/spectrum-design-data-mcp/README.md
tools/spectrum-design-data-mcp/package.json

Enhanced the spectrum-design-data-mcp documentation to align with modern MCP server standards, similar to improvements made in the act-testing-mcp project.
Key improvements include:
- Multiple MCP configuration options with recommended npx usage
- Enhanced security documentation with npm provenance support
- Improved installation section with package integrity verification
- Comprehensive troubleshooting section for common issues
- Dedicated security section with best practices
- Better support section with links to issues and documentation
- Updated package.json with provenance configuration
This change aligns the spectrum-design-data-mcp documentation with improvements made to the act-testing-mcp project to ensure consistency across Adobe's MCP server offerings.
The act-testing-mcp …

feat(spectrum-design-data-mcp): enhance documentation with security and configuration improvements
